[package]
name = "dictionary"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = {workspace = true}
serde = {workspace = true}
chrono = {workspace = true}
tokio = {workspace = true}
reqwest = {workspace = true}
nutype = {version = "0.7", features = ["default", "serde"]}
strum = {version = "0.28", features = ["derive"]}
num_enum = "0.7"

[lib]
path = "src/lib.rs"
name = "internal"